### ISSUE TITLE
Changement de COG en conservant les arrondissements PLM

### ISSUE THREAD

**Issue by mtmx** [antuki/COGugaison#1]
Bravo pour ce package, terriblement utile !
:ok_hand:
Les fonctions de changement de COG (changement_COG_varNum, changement_COG_typo,..) génère-t-elle bien exclusivement des COG sans arrondissements pour Paris Lyon et Marseille ?
Est-ce qu'il serait possible d'ajouter un paramètre permettant de conserver ces arrondissements municipaux dans les tables générées ?
Merci !

**Comment by antuki** [comment]
Merci cher @mtmx 🐴 

Dans les fonctions changement_COG_varNum et changement_COG_typo, si la table en entrée comporte des lignes d'arrondissements pour Paris, Lyon et Marseille, ces lignes seront donc [si les souvenirs que j'ai de la fonction sont bons] laissée telles quelles après exécution de la fonction. Donc je pense que l'utilisation de données comportant les arrondissements ne pose a priori pas de problème ! N'hésite pas à me dire si tu rencontres quand même des problèmes ?

Par ailleurs, j'ai ajouté une ligne de code à nivsupra pour gérer également les cas où la table en entrée contient des arrondissements municipaux (plus besoin de faire un "enlever_PLM" avant un "nivsupra" normalement).

A bientôt pour un test de pull request... 🙀
