### ISSUE TITLE
La table PASSAGE_2007_2008 manque

### ISSUE THREAD

**Issue by coulmont** [antuki/COGugaison#11]
Il semble que la table de passage de 2007 à 2008 manque, alors que le COG 2007 est normalement présent...

```
Error in get(paste0("PASSAGE_", annees[i], "_", annees[i + 1])) : 
  objet 'PASSAGE_2007_2008' introuvable
```

**Comment by antuki** [comment]
Bonjour, 

Effectivement, malheureusement les passages de COG ne sont annuels que depuis 2008 dans ce package. Il n'existe que la table PASSAGE_1999_2008 puis les tables sont ensuite annuelles : 2008_2009 puis 2009_2010 etc jusqu'en 2019. J'avais fait ce choix à l'époque par simplicité d'implémentation des tables de passages mises à disposition mais je sais que cela pose problème dans le cas de données antérieures à 2007 non issues du recensement de la population. 

De quel COG à quel COG voulez-vous passer ? Je peux peut-être vous proposer un code "bidouillage" à partir du package qui réponde à votre besoin. En effet, dans la table 1999_2008 j'ai inscrit les dates d'évènements qui peuvent me permettre de reconstituer les événements entre deux dates. Le seul problème est que dans cette table ne figurent pas les événements multiples (du type si deux communes fusionnent en 2000 et défusionnent en 2007, rien n'apparaît dans la table 1999_2008).

**Comment by coulmont** [comment]
Merci. J'avais cru que la table commençait en 2007 (car la fonction COG_akinator() indique disposer du COG millésime 2007.)
J'ai pu associer "à la main" la poignée de communes qui avaient bougé.

**Comment by antuki** [comment]
Merci de m'avoir signalé pour COG_akinator, car en l'état ça ne me semble pas normal. 
Cela dit, j'ai regardé rapidement le code de la fonction et j'arrive pas à comprendre comment il peut renvoyer que le COG est de 2007.
Est-ce que ça te dérangerait de me mettre un petit reprex pour que j'arrive à comprendre d'où ça vient ? 
Merci !

**Comment by coulmont** [comment]
C'est dans la documentation de ?COG_akinator()  :
<< Les millésimes des COG qui peuvent être utilisés sont à ce stade les suivants : 1968, 1975, 1982, 1990, 1999, 2007 à 2019. >> 
https://github.com/antuki/COGugaison/blob/master/man/COG_akinator.Rd

**Comment by antuki** [comment]
Ah oui en effet, merci beaucoup. C'est a priori juste une erreur de doc, c'est corrigé !
