### ISSUE TITLE
Fonction changement_COG_varNum sur les LIBCOM 

### ISSUE THREAD

**Issue by SarahBenmarhniaOrsB** [antuki/COGugaison#14]
Bonjour, 
merci pour ce package très utile. J'ai une idée d'amélioration, c'est pas vraiment un bug du package mais je ne savais pas où poser la question. 
Lorsque le DEPCOM change, la fonction changement_COG_varNum modifie uniquement la colonne DEPCOM mais pas la colonne LIBCOM. 
Alors on peut se retrouver avec plusieurs lignes pour une même commune si notre base comporte une colonne "LIBCOM". 
Je fais la correspondance "à la main" mais j'avoue que c'est laborieux lorsque l'on travaille sur plusieurs géographies de référence différentes. 
Est-ce que vous pensez que cette amélioration est possible?
Merci beaucoup pour ce partage qui simplifie considérablement notre travail.
Cordialement,
Sarah Benmarhnia

**Comment by antuki** [comment]
Bonjour Sarah. 
Merci pour votre retour. C'est bien ici aussi que vous pouvez poser des questions sur le package. 
Si je comprends bien votre question, il me semble que ce que vous proposez existe déjà en utilisant l'option `libgeo = FALSE` de la fonction `changement_COG_varNum`. Mais peut-être ai-je mal compris votre proposition ? 
Bien à vous ! 
Kim

**Comment by SarahBenmarhniaOrsB** [comment]
Bonjour, 
C'est parfait merci beaucoup pour votre réponse. 
Sarah Benmarhnia
