### ISSUE TITLE
COG_akinator() returns NULL

### ISSUE THREAD

**Issue by Evargalo** [antuki/COGugaison#16]
Bonjour,

la fonction COG_Akinator() me renvoie NULL pour tout jeu de codes communes que je lui transmets sauf le jeu exemple_popcom du package:

    test [1] "69149" "01004" "74012" "38097" "69282" "01283" "69264" "01378" "69135" [10] "38451" exemple_popcom[,1] [1] "01001" "01002" "01004" "01005" "01006" "01007" "01008" "01009" "01010" [10] "01011" "01012" "01013" "01014" "01015" "01016" "01017" "01019" "01021" [19] "01022" "01023" "01024" "01025" "01026" "01027" "01028" "01029" "01030" (...) COG_akinator(vecteur_codgeo = test,donnees_insee=FALSE) NULL COG_akinator(vecteur_codgeo = test,donnees_insee=TRUE) NULL COG_akinator(vecteur_codgeo=exemple_popcom[,1],donnees_insee=TRUE) [1] "COG2014"

Je ne trouve pas dans la documentation si NULL en sortie correspond à une impossibilité de déterminer le millésime, à une erreur dans le format des données en entrée, à un problème d'exécution, etc.

Cdt, Olivier

**Comment by antuki** [comment]
Bonjour, 

Effectivement, cette erreur est due au fait que `COG_akinator` est imparfaite. Elle ne fonctionne à ce stade que sur les bases nationales (https://github.com/antuki/COGugaison/issues/6#issue-342762337). Je pense qu'on pourrait l'adapter assez facilement aux bases régionales mais n'ait pas eu le temps de le faire. Toute suggestion est la bienvenue à ce sujet !

En alternative, il y a la fonction `diag_COG` qui peut fonctionner mais comporter aussi quelques bugs pour quelques cas particuliers !

```
[1] "# ------------------------------"
[1] "# DIAGNOSTIC DE COG"
[1] "# ------------------------------"
[1] "# Synthèse"
[1] "# COG2021"
[1] "# ------------------------------"
[1] "# Diagnostic détaillé"
[1] "# Le fichier compte 10 codes communes."
[1] "# Le diagnostic de COG correspond au COG le plus récent dans lequel l'ensemble des codes communes du fichier en entrée sont présents."


|              | Nombre d'observations|
|:-------------|---------------------:|
|COG2021       |                    10|
|codes uniques |                    10|
```
