### ISSUE TITLE
changement_COG_varNum année 2022

### ISSUE THREAD

**Issue by arnaudfi** [antuki/COGugaison#18]
J'ai essayé aujourd'hui de passer un CODGEO 2021 en géographie 2022, et j'ai obtenu ce code erreur 
"annees ne doit contenir que des années comprises entre 1968 et 2021." 
Est-il possible d'autoriser l'année 2022 ? 
(l'idée pour moi était d'apparier la base permanente des équipements avec la base des bassins de vie 2022, à court terme, je vais utiliser les tables de passage de insee.fr).

Note : j'utilise la version AUS de l'insee

Merci !

**Comment by antuki** [comment]
Bonjour, sauf erreur de ma part, cette issue ne doit plus être d'actualité. 
Merci pour ce signalement !
