### ISSUE TITLE
Difference between insee and COGugaison

### ISSUE THREAD

**Issue by paul-carteron** [antuki/COGugaison#19]
Hi,

Is there somewhere you explain the difference between your dataset and th official [insee dataset](https://www.insee.fr/fr/information/2560452) ?

For 2023 your dataset has 34945 row and insee dataset has 37563.

**Comment by antuki** [comment]
Bonjour,
Certaines tables de passage de l'Insee dont probablement celle dont vous faites référence listent l'ensemble des communes qui ont existé depuis plusieurs dizaines d'années.  C'est pourquoi il y a + 37000 communes alors qu'aujourd'hui le nombre de communes est davantage proche de 35000.

**Comment by paul-carteron** [comment]
Je vois, il y a donc un traitement de la donnée brute par vos soins pour obtenir le dataset final ?

Si c'est le cas, il pourrait être intéressant d'intégrer les données brutes et le script de traitement dans le package ou alors préciser les étapes de nettoyage dans la documentation.

Dans tous les cas, merci pour votre travail !

**Comment by antuki** [comment]
Je repars d'autres tables de passage présentes sur Insee.fr que j'héberge dans les RData du package avec peu de retraitement :
 
https://www.insee.fr/fr/information/7671867 =>   table_passage_annuelle_2024.zip 
https://www.insee.fr/fr/information/7671844 => table-appartenance-geo-communes-24.zip 

Mais en effet, ce peu de retraitement est assez manuel et ne figure pas dans ce répertoire de code.

Merci pour votre retour !
