### ISSUE TITLE
Encodage / UTF8

### ISSUE THREAD

**Issue by joelgombin** [antuki/COGugaison#2]
Bonjour,

tout d'abord ce package est terriblement utile, mille mercis !
Je rencontre un problème d'encodage avec le package : qu'il s'agisse des fichiers source (ex: le fichier [`DESCRIPTION`](https://github.com/antuki/COGugaison/blob/master/DESCRIPTION) ou des jeux de données d'exemple (ex : `exemple_popcom %>% as_tibble()`), les signes diacritiques ne sont pas correctement retranscris : 
```r
> exemple_popcom %>% as_tibble
# A tibble: 36,664 x 6
   CODGEO LIBGEO                       P12_POP SUPERF typoA    typoB
   <chr>  <chr>                          <int>  <int> <chr>    <chr>
 1 01001  "L'Abergement-Cl\xe9menciat"     777     16 CLASSE 2 F    
 2 01002  L'Abergement-de-Varey            235      9 CLASSE 3 D    
 3 01004  "Amb\xe9rieu-en-Bugey"         14233     25 CLASSE 1 B    
 4 01005  "Amb\xe9rieux-en-Dombes"        1642     16 CLASSE 3 F    
 5 01006  "Ambl\xe9on"                     110      6 CLASSE 4 E    
 6 01007  Ambronay                        2437     34 CLASSE 5 A    
 7 01008  Ambutrix                         739      5 CLASSE 3 C    
 8 01009  Andert-et-Condon                 338      7 CLASSE 2 F    
 9 01010  Anglefort                       1069     29 CLASSE 4 E    
10 01011  Apremont                         385     15 CLASSE 4 B    
# ... with 36,654 more rows
```

Peut-être le package a-t-il été développé avec Windows, qui n'utilise pas l'UTF-8 comme encodage par défaut ?

**Comment by joelgombin** [comment]
(de manière complémentaire, je me permets de suggérer d'inclure dans le code source du package les scripts permettant de générer les jeux de données inclus dans le package, ça me permettrait le cas échéant de faire une PR avec un fix :) )

**Comment by joelgombin** [comment]
(par ailleurs les erreurs d'encodage apparaissent aussi dans les exemples de la doc des fonctions, e.g. https://antuki.github.io/COGugaison/reference/apparier_COG.html)

**Comment by antuki** [comment]
Merci Joël pour tes retours. 

Plusieurs points donc : 

- Je ne suis pas sûre d’avoir bien compris ce que tu entendais en disant d’ « inclure dans le code source du package les scripts permettant de générer les jeux de données ». En fait,  à ce stade, je fais un simple read.csv de fichiers csv que je stocke sur mon poste pour générer des Rdata. Bon, bien sûr j’ai quelques programmes pour générer ces csv à partir des données Insee mais c’est encore un vrai patchwork car j’ai dû effectuer des vérifs un peu manuelles pour certains cas particuliers quand je commençais à appréhender les données donc pour le moment je voudrais me contenter de mettre en ligne les tables construites (mais le projet à termes sera bien de tout mettre mais je ne sais pas quand...). En lisant rapidement ton lien, j’ai commencé à vouloir mettre les csv dans inst/extdata mais ça double la taille du package qui est déjà assez gros (et le install_github devenait vraiment vraiment long…). L’idée à termes sera de rajouter encore des tables de passages (annuelles avant 2008) donc il faudra que je commence à essayer de réfléchir à optimiser au max la taille des données. 

- Pour les erreurs d’encodage dans pkgdown, j’en ai conscience mais hélas je n’ai jamais trouvé de solution idéale. Il y a un mix entre un problème d’encodage dû au fait que je travail sur windows avec également des problèmes d’encodages dans le build_reference de pkgdown : (cf. issue ici https://github.com/r-lib/pkgdown/issues/339). Il y a aussi des problèmes d’encodage dans la doc directement dans R, notamment l’index du package, là encore j’ai cru comprendre que c’était dû à windows. Bref, si tu as une solution miracle pour résoudre le problème, elle sera la bienvenue… Je poserai peut-être également la question à l’occasion en issue sur pkgdown.

- Pour ta question principale : j’ai changé l’encodage des tables en UTF8 (normalement) en utilisant le read_csv du tidyverse plutôt que le basic read.csv. Il paraît qu’il permet mieux de gérer les problèmes d’encodage de windows alors j’ai testé. J’espère donc que ça a bien marché (je ne vois pas la différence sur mon windows mais j'ai regardé aussi rapidement sur un mac)

**Comment by cderv** [comment]
Bonjour, 

L'encodage est un vrai défi ! 

Pour le problème sur pkgdown, c'est enfin fusionné, ça devrait donc fonctionner maintenant. A tester donc.

Autrement, pour gérer l'encodage au mieux pour  nous français sur un PC windows quand on crée des packages en français, le REX que j'en fait est de bien s'assurer 

+ que le plus de scripts est indiqué comme étant utf-8 (comme déjà fait avec `@encoding UTF-8`, `Encoding: UTF-8` et `%\VignetteEncoding{UTF-8}`)
+ qu'aucune fonction ne s'éxécute par avec l'encodage par défaut `getOption("encoding")` qui sous windows est particulier. Par exemple, j'ai souvent rencontré des soucis avec `rmarkdown::render` qui demande de préciser en entrée l'encodage sinon ça peut causer des problèmes.

Pour l'index du package, il me semble qu'il est généré avec `tools::Rdindex()`. Je crois avoir résolu ce problème une fois, mais il faut que je retrouve. Si c'est le cas, je vous dit.

**Comment by antuki** [comment]
Merci Christophe pour tes astuces, je vais pouvoir creuser tout cela à l'occasion !

Et oui je suis intéressée si tu retrouves l'astuce pour contrer l'index au mauvais encodage généré par Rdindex().

**Comment by cderv** [comment]
Hello !
J'ai cherché un peu ce week end et ce n'est pas évident. Il semble y avoir un problème dans la fonction qui créé le fichier HTML. Tout est bien UTF8 mais le fichier HTML généré contient des caractère en latin1. Il n'y a pas l'air d'avoir beaucoup de package sur le CRAN avec du français partout (DESCRIPTION + MANUEL). Je pense que c'est du aussi parcequ'on créé le package sur un système français. 
A suivre donc, mais pas de solutions pour l'index pour le moment ! C'est une fonction de base de R, et ça ne se modifie pas simplement, dur de creuser.

**Comment by ddotta** [comment]
Package très prometteur avec des fonctionnalités très utiles ! Merci
A quand une publication sur le CRAN ?
Par ailleurs, je voulais savoir s'il serait possible de mettre à disposition les "windows binaries" au format zip pour pouvoir embarquer le package dans des applications style shiny ?

**Comment by antuki** [comment]
Merci pour ce message @ddotta. J'ai ouvert une issue indépendante (#3)

**Comment by antuki** [comment]
Problèmes d'encodages réglés grâce aux nouvelles versions de pkgdown.
