### ISSUE TITLE
Problème COG2022_insee

### ISSUE THREAD

**Issue by Grivault** [antuki/COGugaison#20]
Bonjour, 
Tout d'abord, merci pour votre travail sur ce package qui nous fait gagner beaucoup de temps.
Sauf erreur de ma part, les tables COG2022_insee et COG2022 sont identiques à celles de l'année 2021 alors qu'il y a eu des modifications de communes sur cette période.

Cordialement,
Camille

**Comment by antuki** [comment]
Bonjour Camille @Grivault, 
Merci pour ce signalement, les tables de COG2022 étaient en effet par erreur un duplicata des tables de 2021. J'ai récupéré les tables 2022 dans mes archives et les ai remplacées dans le commit https://github.com/antuki/COGugaison/commit/57d68fba09a0a95bf3e454365218323cbc989673 merci !
