### ISSUE TITLE
Probleme dans COG_akinator

### ISSUE THREAD

**Issue by vincentL23** [antuki/COGugaison#21]
Bonjour,

Merci beaucoup pour votre package, on se sent moins seul pour travailler sur le COG.
J'ai l'impression qu'il y a une erreur ligne 65 de la fonction COG_akinator :

if (length(setdiff(vecteur_codgeo_COG,vecteur_codgeo))==0) { # new : avant all(vecteur_codgeo %in% vecteur_codgeo_COG)

Il vaudrait mieux écrire setdiff(vecteur_codgeo,vecteur_codgeo_COG)
en tout cas en changeant le code cela marchait de mon côté, et c'est plus cohérent par rapport à all(vecteur_codgeo %in% vecteur_codgeo_COG)

Bien cordialement,

**Comment by antuki** [comment]
Merci @vincentL23 pour votre suggestion. Je pense que vous avez raison. 
J'ai donc adapté le code en conséquence dans le dernier commit (https://github.com/antuki/COGugaison/commit/37a6d4c9ca0d608bb4f2b64aaf1c56c097a7f813)
Merci encore !
