### ISSUE TITLE
COguaison pour récupérer des données de référence sur les communes

### ISSUE THREAD

**Issue by cderv** [antuki/COGugaison#7]
Bonjour ,

Comme j'ai un cas sur lequel j'ai besoin d'associer communes + département, je me suis dit pourquoi ne pas utiliser ce package plutôt qu'allait télécharger les données de l'INSEE que je ne connais pas bien. 

Du coup, j'ai pas de donnée sous la main et je souhaite avoir une table avec les codes des communes, leur libéllé, les n° de départements et leur libellé. 

J'ai donc essayé d'utiliser la fonction `niv_supra` sans aggrégation en me disant que ça pouvait servir

``` r
library(COGugaison)
nivsupra(COG2016, codgeo_entree = "CODGEO", COG = "2016", agregation = FALSE, nivsupra = "DEP")
#> Error in `[.data.frame`(table_sortie, , c(colnames(table_entree), nivsupra_nom, : undefined columns selected
```

<sup>Created on 2019-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A priori ça semble pas prévu pour puisque la table d'entrée à un nom identique aux tables qui sont fusionnés. 

Le problème est là: 
https://github.com/antuki/COGugaison/blob/0a0cab8a23bcdae05de473903f1590b23c131549/R/nivsupra.R#L87

Il y a un nom de colonne `LIBGEO` qui est devenu `LIBGEO.x` au moment d'un des `merge`

Si je change les noms de la table d'entrée, c'est ok
``` r
library(COGugaison)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
COG2016 %>% 
  select(code_commune = CODGEO, lib_commune = LIBGEO) %>%
  nivsupra(COG = "2016", agregation = FALSE, nivsupra = "DEP") %>%
  as_tibble()
#> # A tibble: 35,885 x 4
#>    code_commune lib_commune            DEP_code_commune DEP_nom_code_commu~
#>    <chr>        <chr>                  <chr>            <chr>              
#>  1 01001        L'Abergement-Clémenci~ 01               Ain                
#>  2 01002        L'Abergement-de-Varey  01               Ain                
#>  3 01004        Ambérieu-en-Bugey      01               Ain                
#>  4 01005        Ambérieux-en-Dombes    01               Ain                
#>  5 01006        Ambléon                01               Ain                
#>  6 01007        Ambronay               01               Ain                
#>  7 01008        Ambutrix               01               Ain                
#>  8 01009        Andert-et-Condon       01               Ain                
#>  9 01010        Anglefort              01               Ain                
#> 10 01011        Apremont               01               Ain                
#> # ... with 35,875 more rows
```

<sup>Created on 2019-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Il y surement qqch à améliorer ici même si c'est un peu un _edge case_ 

Est ce que je devrais plutôt récupérer ce type de données autre part ?

**Comment by antuki** [comment]
Effectivement, pour que ça fonctionne il faut enlever la colonne LIBGEO de la table initiale que tu veux apparier avec les niveaux supra. 
J'ai réfléchi quelques secondes dessus et je ne sais pas comment je peux faire facilement pour faire un merge plus optimal quand le table initiale contient un nom de colonne contenu dans la base avec laquelle elle est appariée via nivsupra. 

Et pour répondre à ta question, tu peux précisément utiliser directement cette fameuse base appelée table_supracom_2016 contenue dans le package ainsi que la table associée qui contient les libellés si tu as besoin de ces libellés : libelles_supracom_2016. 

J'espère avoir répondu à ta question.

**Comment by cderv** [comment]
oui merci. j'ai fais en croisant les tables moi même du coup. 
Je suppose que c'est un cas bizarre ce que je voulais faire. 🤔
