### ISSUE TITLE
Clarification dans la doc sur le COG par défaut

### ISSUE THREAD

**Issue by cderv** [antuki/COGugaison#8]
Dans `niv_supra`, on a 
> COG  indique l'année de COG de la table communale considérée.  (exemple 2014). Années possibles : de 2008 à 2019. Par défaut, vaut  2019.

source : https://antuki.github.io/COGugaison/reference/nivsupra.html

mais dans GET STARTED on a 

> La fonction nivsupra permet d’agréger les tables de données communales à de nombreux échelons supra-communaux administratifs (EPCI, arrondissements, cantons-villes, départements, régions) ou d’étude (bassins de vie, zones d’emploi, unités urbaines, aires urbaines) en indiquant le COG de la base de donnée en entrée et de référence des niveaux supra-communaux grâce au paramètre COG (**par défaut renvoie le COG renvoyé par COG_akinator)**. 

source : https://antuki.github.io/COGugaison/articles/COGugaison.html#agreger-des-tables-de-donnees-communales-a-des-echelons-supra-communaux

J'ai loupé quelque chose ou le Get Started est à mettre à jour ? 
Merci.

**Comment by antuki** [comment]
Effectivement, c'est une erreur dans GET STARTED. Le paramètre de la fonction est bien par défaut la dernière année de référence (annee_ref) qui est actuellement 2019. Je vais mettre la vignette à jour et j'en profiterai pour la reparcourir car il y a peut-être des anciennes années de COG qui traînent ça et là.
