### ISSUE TITLE
Gestion des scissions communales

### ISSUE THREAD

**Issue by vdahinger** [antuki/COGugaison#9]
Bonjour,

J'utilise depuis peu de temps le package COGugaison et je m'interroge sur la gestion des scissions communales...
Dans le cas de la fonction changement_COG_varNum, si une commune est séparée en deux, nous aurons un nouveau CODGEO, que devient la variable numérique ? est-elle divisée entre les deux communes ou attribue-t-on la même valeur pour chaque CODGEO ?

Merci pour votre réponse.

Virginie

**Comment by antuki** [comment]
Bonjor, 

Pour les séparations de communes, les variables numériques sont divisées entre les deux communes proportionnellement à la population de la commune l'année qui suit la défusion. 

Un exemple schématique est présent sur la slide 9 de cette présentation : https://antuki.github.io/slides/180306_RLadies_COGugaison_carto/180306_RLadies_COGugaison_carto.html#9 

Ces proportions correspondent à la colonne "ratio" des tables du package appelées PASSAGE_20XX_20XX. 

J'espère avoir répondu à vos interrogations.

**Comment by vdahinger** [comment]
Parfait, merci beaucoup.
